config/routes.rb
Rails.application.routes.draw do
  resources :discovers do
      collection do
        match 'search', action: :index, as: :search, via: [:get, :post]
      end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discover.rb
# coding: utf-8
class Discover < ApplicationRecord
  enum trigger: {human: 0, magnetic: 1, lumen: 2, temp: 3}

  validates :obs_at, presence: true
  validates :trigger, presence: true
  validates :magnetic_vol, presence: true
  validates :lumen_vol, presence: true
  validates :temp_vol, presence: true

  class Search
    include ActiveModel::Model
    include ActiveModelBase

    attr_accessor :obs_at_from, :obs_at_to, :triggers, :magnetic_vol_from, :magnetic_vol_to, :lumen_vol_from, :lumen_vol_to, :temp_vol_from, :temp_vol_to, :human
         type_int :magnetic_vol_from, :magnetic_vol_to, :lumen_vol_from, :lumen_vol_to, :temp_vol_from, :temp_vol_to
        type_bool :human

    def search(page)
      model = Discover.active.order(id: :desc)

      model = model.between(:obs_at, self.obs_at_from, self.obs_at_to)

      self.triggers.try :delete, ""
      if self.triggers.present?
        model = model.where(trigger: self.triggers)
      end

      if self.human.present?
        model = model.where(human: self.human )
      end

      model = model.between(:magnetic_vol, self.magnetic_vol_from, self.magnetic_vol_to)

      model = model.between(:lumen_vol, self.lumen_vol_from, self.lumen_vol_to)

      model = model.between(:temp_vol, self.temp_vol_from, self.temp_vol_to)

      model.page(page)
    end
  end
end

app/controllers/discovers_controller.rb
# coding: utf-8
class DiscoversController < ApplicationController
  before_action :set_discover, only: [:show, :edit, :update, :destroy]

  # GET /discovers
  def index
    @search_discover = Discover::Search.new(search_params)
    @discovers = @search_discover.search(params[:page])
  end

  # GET /discovers/1
  def show
  end

  # GET /discovers/new
  def new
    @discover = Discover.new
  end

  # GET /discovers/1/edit
  def edit
  end

  # POST /discovers
  def create
    @discover = Discover.new(discover_params)

    if @discover.save
      redirect_to @discover, notice: 'Discover was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /discovers/1
  def update
    if @discover.update(discover_params)
      redirect_to @discover, notice: 'Discover was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /discovers/1
  def destroy
    @discover.logical_delete!
    redirect_to discovers_url, notice: 'Discover was successfully destroyed.'
  end

  private
    # Search params
    def search_params
      if params[:discover_search]
        params.require(:discover_search).permit(:obs_at_from, :obs_at_to, {triggers: []}, :magnetic_vol_from, :magnetic_vol_to, :lumen_vol_from, :lumen_vol_to, :temp_vol_from, :temp_vol_to, :human)
      else
        {}
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_discover
      @discover = Discover.active.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def discover_params
      params.require(:discover).permit(:obs_at, :trigger, :human, :magnetic_vol, :lumen_vol, :temp_vol, :lock_version)
    end
end

app/views/discovers/_form.html.erb
<%-
only_show ||= false
url =
  if @discover.new_record?
    discovers_path
  else
    discover_path(@discover)
  end
-%>
<div class="card bg-light mb-3"><div class="card-body">
  <%= simple_form_for(@discover, url: url) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :obs_at,
            disabled: only_show
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :trigger,
            disabled: only_show
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :human,
            disabled: only_show
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :magnetic_vol,
            disabled: only_show
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :lumen_vol,
            disabled: only_show
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :temp_vol,
            disabled: only_show
          ) %>
        </div>
      </div>
      <%= f.hidden_field :lock_version %>
    </div>

    <%- unless only_show -%>
      <div class="form-actions row justify-content-around">
        <%= f.button :submit, class: "btn btn-primary col-md-3 col-sm-5" %>
      </div>
    <%- end -%>
  <% end %>
</div></div>

app/views/discovers/edit.html.erb
<%= render 'form', discover: @discover %>

<div class="row justify-content-around">
  <%= link_to '戻る', discovers_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
  <%= link_to '削除', discover_path(@discover), method: :delete, data: { confirm: '削除します。よろしいですか？' }, class: 'btn btn-danger col-md-2 col-sm-4'  %>
</div>

app/views/discovers/index.html.erb
    <!-- ????? -->
    <!-- <div id="sensor">aaa</div> -->

    <!-- ???????? -->
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <td>
          <a>人感センサ</a>
          <br />
          <span id="sensor">---</span>
        </td>
        <td>
          <a>磁気センサ</a>
          <br />
          <span id="rawData0">init</span>
          <br />
          <span id="voltage0">init</span>
        </td>
        <td>
          <a>光センサ</a>
          <br />
          <span id="rawData1">init</span>
          <br />
          <span id="voltage1">init</span>
        </td>
        <td>
          <a>温度センサ</a>
          <br />
          <span id="rawData2">init</span>
          <br />
          <span id="voltage2">init</span>
        </td>
        <td>
      </tr>

      <tr></tr>
    </table>
<div class="card bg-light mb-3"><div class="card-body">
  <%= simple_form_for @search_discover, url: search_discovers_path do |f| %>
    <div class="form-inputs">
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :obs_at,
            as: :date_range
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :triggers,
            as: :check_boxes,
            collection: Discover.triggers_i18n.invert
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :human,
            as: :boolean
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :magnetic_vol,
            as: :int_range
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :lumen_vol,
            as: :int_range
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :temp_vol,
            as: :int_range
          ) %>
        </div>
      </div>
    </div>
    <div class="form-actions search d-flex justify-content-end">
      <%= f.button :submit, class: "btn btn-primary col-md-3 col-sm-5", value: "検索" %>
    </div>
  <% end %>
</div></div>

<div class="card bg-light mb-3"><div class="card-body">
  <%- if @discovers.blank? -%>
    <p><%= t("activerecord.models.discover") %>は登録されていません。</p>
  <%- else -%>
    <div class="text-right">
      <%= page_entries_info @discovers %>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th><%= Discover.human_attribute_name :obs_at %></th>
            <th><%= Discover.human_attribute_name :trigger %></th>
            <th><%= Discover.human_attribute_name :human %></th>
            <th><%= Discover.human_attribute_name :magnetic_vol %></th>
            <th><%= Discover.human_attribute_name :lumen_vol %></th>
            <th><%= Discover.human_attribute_name :temp_vol %></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @discovers.each do |discover| %>
            <tr>
              <td><%= link_to discover.obs_at, "/photos/#{discover.obs_at.strftime('%Y%m%d_%H%M%S')}.jpg" %></td>
              <td><%= discover.trigger %></td>
              <td><%= discover.human %></td>
              <td><%= discover.magnetic_vol %></td>
              <td><%= discover.lumen_vol %></td>
              <td><%= discover.temp_vol %></td>
              <td><%#= link_to '編集', edit_discover_path(discover), class: 'btn btn-primary btn-block' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row justify-content-around">
      <%= paginate @discovers %>
    </div>
  <%- end -%>
</div></div>

<div class="row justify-content-around">
  <%= link_to '新規作成', new_discover_path, class: 'btn btn-info col-md-3 col-sm-5' %>
</div>

app/views/discovers/new.html.erb
<%= render 'form', discover: @discover %>

<div class="row justify-content-around">
  <%= link_to '戻る', discovers_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
</div>

app/views/discovers/show.html.erb
<%= render "form", only_show: true %>

<div class="row justify-content-around">
  <%= link_to '戻る', discovers_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
  <%= link_to '編集', edit_discover_path(@discover), class: 'btn btn-success col-md-2 col-sm-4' %>
</div>